language: java

branches:
  only:
    - master

after_success:
  - mvn deploy --settings src/main/config/travis-settings.xml

env:
  global:
    - secure: "atM6roky/bH3XoWHwjK9mYY9+kD4/Cw4ixFe10OOphYOo7/GVKeStpwOXr/R9c3rSDoIcLWiHthB3sz9Fa5LBcVJty6TnSJFaE50rrDEchZSKu5ZqWN2kW9xgBsim1rzqlF+0h0CIjC909H9gkk09dj/L8V8u58KZhMixHpzyOs="
    - secure: "L6TCpIdrZScEIv1RtloFhkAxFGIZYX7kbmUnd56kkMak+OHUtBtSibixeo/Brf5Zyb+5RFM0s6WxC98ymiqxVxVFI9s16JYybd6eycMYgG2/9VIRif/FEjsZzaEdIUoyHyMxOYZKRfxxH2e8/tKA0yVPzWBfGep9eV3zpQp2e2k="